config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/inventor-cmd/argocd-practice.git 
      targetRevision: main
      path: app-of-apps/helm-app

applications:
  - name: nginx
    path: app-of-apps/manifests/nginx
  - name: monitoring
    path: app-of-apps/manifests/monitoring
  - name: myapp
    namespace: myapp
    path: app-of-apps/manifests/myapp
  #- name: pre-post-sync
  #- name: sock-shop
  #- name: sync-waves