apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # cleans up on delete
spec:
  project: default
  source:
    repoURL: https://github.com/inventor-cmd/argocd-practice.git 
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true       # remove resources deleted from Git
      selfHeal: true    # revert manual kubectl changes
    syncOptions:
      - CreateNamespace=true    # auto-create namespace
      - ServerSideApply=true    # avoids annotation size issues
